### ISSUE TITLE
Add fork algorithm

### ISSUE THREAD

**Issue by k664293927** [luminousmining/miner#28]
I hope to add the MEOWPOW algorithm, which is an adaptation of the KAWPOW algorithm

**Comment by 1460293896** [comment]
Hi, have you compiled it yet? I am unable to compile successfully here

**Comment by luminousmining** [comment]
@1460293896 if you need talk to compil you can come on discord https://discord.gg/uTNRBFVz
I added link ;)

**Comment by luminousmining** [comment]
WIP: https://github.com/luminousmining/miner/pull/71

**Comment by luminousmining** [comment]
Merged. Meowpow on NVIDIA and AMD.
