### ISSUE TITLE
is there anyway run without nvrtc64_120_0.dll

### ISSUE THREAD

**Issue by SpiritedAwayLab** [luminousmining/miner#54]
hi, just wondering, is there anyway that the EXE can run without nvrtc64 dll in system? i have already built the exe from code. So if there is any configure can be reset so that avioid nvrtc64 dll ， i am able to do that .

**Comment by luminousmining** [comment]
Actually now. Did you use miner with rig AMD or NVIDIA ?

**Comment by SpiritedAwayLab** [comment]
y. Nvidia and AMD in windows. Is there anyway like change compile method like use nvcc or something, so the miner can run only with exe itself?

**Comment by luminousmining** [comment]
Ok thanks, I will change it.

**Comment by SpiritedAwayLab** [comment]
hi, any idea how to achieve  it?

**Comment by luminousmining** [comment]
ctuellement il n'est pas possible de lancé luminousminer sans nvrtc il faut installer cuda meme sur les rig avec AMD uniquemnet. Une option serait d'utiliser HiveOS sinon.

Il faut changer le comportement dans le code source.
```
find_library(CUDA_NVRTC_LIBRARY name nvrtc PATHS ${CUDA_TOOLKIT_ROOT_DIR} PATH_SUFFIXES ${CUDA_TOOLKIT_PATH_SUFFIXES} NO_DEFAULT_PATH REQUIRED)
```
Il faudrait charger la nvrtc via LoadLibrary.

**Comment by luminousmining** [comment]
draft : https://github.com/luminousmining/miner/pull/59  
You can compil with option `BUILD_AMD` and `BUILD_NVIDIA`.  

Set `BUILD_NVIDIA` at OFF for you rigs using only `AMD`.  
I will release new exes.

**Comment by SpiritedAwayLab** [comment]
ok i see.  thanks anyway.  I am going to use it on NVIDIA, though. 
BTW, are you planing to add iron fish algorithm?

**Comment by luminousmining** [comment]
For iron fish, can you open issue and link official miner open source please.
