### ISSUE TITLE
Trying to reduce GPU usage

### ISSUE THREAD

**Issue by SpiritedAwayLab** [luminousmining/miner#60]
Hi, i am trying to reduce the GPU usage ( like 75% or half ) so that PC can be used when mining. For other miner, there will be a config parameter : intensity.

I am trying to achieve it by coding. I tried to set:
setThreads(256u);
setBlocks(4096u); 

once I chagne threads to like  128 or 64 or other, all the shares calculated will be invaild. but blocks will not.  I have no idea, how could it happen. can you figure it out?

**Comment by SpiritedAwayLab** [comment]
Kawpow on 3080ti

**Comment by luminousmining** [comment]
https://github.com/luminousmining/miner/pull/63  
I added options `--threads=X` and `--blocks=X` available only for NVIDIA and KAWPOW atm.  

I tested change `threads` only and kawpow create invalid share.  
I tested change `blocks` only and it's ok.  

ATM you can use `--blocks=128` to reduce GPU usage.

**Comment by SpiritedAwayLab** [comment]
thanks a lot.

i just confused why this happened.  #change threads only and kawpow create invalid share.

**Comment by SpiritedAwayLab** [comment]
If you don't have idea why this happend. I have another question, why you
set 256 threads here?

LuminousMining ***@***.***> 于 2024年9月6日周五 21:34写道：

**Comment by luminousmining** [comment]
I used 256 to have the largest possible occurrancy for the most GPUs possible.
It would be necessary to use a function that calculates the number of threads based on the number of registers used.

The theoretical minimum number of threads is 16, in theory we should be able to set 16/32/64/128/256.

**Comment by luminousmining** [comment]
Ho OK ! I know why we need to use 256 !

```cpp
__device__ __forceinline__
void initialize_header_dag(
    uint32_t const group_id,
    uint32_t* __restrict__ const header_dag,
    uint32_t const* __restrict__ const dag)
{
    #pragma unroll
    for (uint32_t i = 0u; i < 16u; ++i)
    {
        uint32_t const indexDAG = i * 256u + group_id;
        uint32_t const itemDag = dag[indexDAG];
        header_dag[indexDAG] = itemDag;
    }
    __syncthreads();
}
````

I initialized the header in shared memory by group of 256 THREADS ! ` i * 256u + group_id;`  
I have to enter this generic function depending on the number of threads used.

@SpiritedAwayLab Thank you to spot this bug !

**Comment by SpiritedAwayLab** [comment]
Before I post the issue, I tried modifying every instance of '256u' to '128u' in the code, include search.cu in execute dir. But I found that it still doesn't work.

`uint32_t const indexDAG = i * 256u + group_id;`
to
`uint32_t const indexDAG = i * 128u + group_id;`

then  modify the code in  
`bool resolver::ResolverNvidiaProgPOW::updateConstants(`
`setThreads(128u);`

then i compile the miner solution 
unfortunately it doesn't work

Have you had any success with it?

**Comment by SpiritedAwayLab** [comment]
i tried three cases:
case 1: 
search.cu:
`uint32_t const indexDAG = i * 128u + group_id;`

bool resolver::ResolverNvidiaProgPOW::updateConstants
`setThreads(256u);`

result: Not working

case 2
search.cu:
`uint32_t const indexDAG = i * 128u + group_id;`

bool resolver::ResolverNvidiaProgPOW::updateConstants
`setThreads(128u);`

result: Not working

case 3: 
search.cu:
`uint32_t const indexDAG = i * 256u + group_id;`

bool resolver::ResolverNvidiaProgPOW::updateConstants
`setThreads(256u);`

result: works! 

Seems there is another param control the thread or something.

**Comment by luminousmining** [comment]
PR : https://github.com/luminousmining/miner/pull/66

Now you can use `--threads=128` ;) The initialize header is dynamic now.  
Can you pull main and give me feedback.

**Comment by luminousmining** [comment]
> i tried three cases: case 1: search.cu: `uint32_t const indexDAG = i * 128u + group_id;`
> 
> bool resolver::ResolverNvidiaProgPOW::updateConstants `setThreads(256u);`
> 
> result: Not working
> 
> case 2 search.cu: `uint32_t const indexDAG = i * 128u + group_id;`
> 
> bool resolver::ResolverNvidiaProgPOW::updateConstants `setThreads(128u);`
> 
> result: Not working
> 
> case 3: search.cu: `uint32_t const indexDAG = i * 256u + group_id;`
> 
> bool resolver::ResolverNvidiaProgPOW::updateConstants `setThreads(256u);`
> 
> result: works!
> 
> Seems there is another param control the thread or something.

You need to modify `16u` loot index too ;)
4096 (cache loaded) / 256(threads) = 16. Each threads load 16 items of dags.

**Comment by SpiritedAwayLab** [comment]
That is brilliant!  It works! 
Many thanks
