### ISSUE TITLE
all share when mining Ergo  is invalid (reject)

### ISSUE THREAD

**Issue by lovemining** [luminousmining/miner#74]
Dear LuminousMining 

Thanks for making the great open source for ERGO, I compiled your miner and was trying play with ergo 

However, all share is invalid. Do you have any idea to fix it?

Thank you very much and looking to see reply from you!

I copy and pasted the log under this message

(2024/Dec/04)(16:03:41)(i) - New Job[3d80]
(2024/Dec/04)(16:03:44) - ======================================= HASHRATE ========================================
(2024/Dec/04)(16:03:44) - | Type   | ID | Pci | Algorithm   | Pool                    | Hashrate | Valid | Reject |
(2024/Dec/04)(16:03:44) - | NVIDIA | 0  | 7   | autolykosv2 | ergo-asia1.nanopool.org | 43.85MH  | 0     | 16     |
(2024/Dec/04)(16:03:44) - =========================================================================================

(2024/Dec/04)(16:03:52)(i) - Device[0]: Update memory in 10687ms
(2024/Dec/04)(16:03:54) - ======================================= HASHRATE ========================================
(2024/Dec/04)(16:03:54) - | Type   | ID | Pci | Algorithm   | Pool                    | Hashrate | Valid | Reject |
(2024/Dec/04)(16:03:54) - | NVIDIA | 0  | 7   | autolykosv2 | ergo-asia1.nanopool.org | 43.85MH  | 0     | 16     |
(2024/Dec/04)(16:03:54) - =========================================================================================

(2024/Dec/04)(16:03:57)(i) - New Job[3d81]
(2024/Dec/04)(16:04:04) - ======================================= HASHRATE ========================================
(2024/Dec/04)(16:04:04) - | Type   | ID | Pci | Algorithm   | Pool                    | Hashrate | Valid | Reject |
(2024/Dec/04)(16:04:04) - | NVIDIA | 0  | 7   | autolykosv2 | ergo-asia1.nanopool.org | 43.85MH  | 0     | 16     |
(2024/Dec/04)(16:04:04) - =========================================================================================

(2024/Dec/04)(16:04:08)(i) - Device[0]: Update memory in 10956ms
(2024/Dec/04)(16:04:14) - ======================================= HASHRATE ========================================
(2024/Dec/04)(16:04:14) - | Type   | ID | Pci | Algorithm   | Pool                    | Hashrate | Valid | Reject |
(2024/Dec/04)(16:04:14) - | NVIDIA | 0  | 7   | autolykosv2 | ergo-asia1.nanopool.org | 43.85MH  | 0     | 16     |
(2024/Dec/04)(16:04:14) - =========================================================================================

(2024/Dec/04)(16:04:24) - ======================================= HASHRATE ========================================
(2024/Dec/04)(16:04:24) - | Type   | ID | Pci | Algorithm   | Pool                    | Hashrate | Valid | Reject |
(2024/Dec/04)(16:04:24) - | NVIDIA | 0  | 7   | autolykosv2 | ergo-asia1.nanopool.org | 43.85MH  | 0     | 16     |
(2024/Dec/04)(16:04:24) - =========================================================================================

**Comment by luminousmining** [comment]
Duplicate issue : https://github.com/luminousmining/miner/issues/69
We have problem with autolykosv2 but I dont understand the problem.

**Comment by luminousmining** [comment]
If you or someone find a miner open-source autolykosv2 works I can fix and improve performance.

**Comment by lovemining** [comment]
thanks for your information

**Comment by lovemining** [comment]
@luminousmining I found that this fork is mining well ERGO, GPU

https://github.com/luminousmining/Autolykos2_NV_Miner.git

**Comment by luminousmining** [comment]
Did you tested it ?
If yes can you share me your protocol ?
It's my fort but I have all share invalid too.

**Comment by lovemining** [comment]
![image](https://github.com/user-attachments/assets/e2f5abd8-555b-4341-891a-fd4a2ce0a958)
![image](https://github.com/user-attachments/assets/e512c5a4-6bc9-4c2b-b0c7-87733cf6319d)
yes, I have tested and got valid shares.

**Comment by luminousmining** [comment]
Hooo!!!!
Can you share me your config file please (remove confidential information).
I will re test it to night.

**Comment by lovemining** [comment]
I'm using proxy
1. Running proxy command line
`./ErgoStratumProxy_Linux -s hk.ergo.herominers.com -p 10250 -u MY_TEST_WALLET.default`

2. config.json at the same auto.out direction
```
cat config.json 
{ "node": "http://127.0.0.1:3000" 
```

`then run ./auto.out`

**Comment by luminousmining** [comment]
I think I have problem !

Proxy:
```
wget https://github.com/mhssamadani/ErgoStratumProxy/releases/download/1.2.1/ErgoStratumProxy_Linux --no-check-certificate
```
```
./ErgoStratumProxy_Linux -s hk.ergo.herominers.com -p 10250 -u 9fFUw6DqRuyFCv13nQyoDuDz4TiR4GvVvWRcSvqzs39eBVcb5S1.default
```

Miner:
```sh
git clone git@github.com:luminousmining/Autolykos2_NV_Miner.git
cd Autolykos2_NV_Miner
cd secp256k1
make
```
```
./auto.out
```

Result:
```
2024-12-11 21:47:54,461 INFO [main thread] Using 1 GPU devices
2024-12-11 21:47:54,461 INFO [main thread] Using configuration file ./config.json
2024-12-11 21:47:54,461 INFO [main thread] Block getting URL:
   http://127.0.0.1:3000/mining/candidate
2024-12-11 21:47:54,461 INFO [main thread] Solution posting URL:
   http://127.0.0.1:3000/mining/solution
2024-12-11 21:47:54,467 INFO [main thread] Got new block in main thread, block data: {"MSG":"3A9C9D49F5A3815FE7E933CB15C85F3A41026C1A3D17A958AC647E2928EF967D","B":28948022309329048855892746252171976963209391069768726095651290785379,"EXTRANONCE1":"8A67","EXTRANONCE2SIZE":6,"HEIGHT":1415089}
2024-12-11 21:47:54,733 INFO [GPU 0 miner] GPU 0 started
2024-12-11 21:48:07,682 INFO [GPU 0 miner] sol not passed
2024-12-11 21:48:07,682 INFO [GPU 0 miner]  problem in verify solution, nonce: 9972939901049711312
2024-12-11 21:48:38,920 INFO [GPU 0 miner] sol not passed
2024-12-11 21:48:38,920 INFO [GPU 0 miner]  problem in verify solution, nonce: 9972939904560340700
```

All solution failed `sol not passed`.

**Comment by luminousmining** [comment]
Ho ok !
I have not see you have too `sol not passed` ;)
I will look it :D 
My Bad

**Comment by luminousmining** [comment]
I found the problem.
I must add function `bool AutolykosAlg::RunAlg(` to double check the share validity.
I will implement it.

**Comment by lovemining** [comment]
That is great catch

**Comment by luminousmining** [comment]
https://github.com/luminousmining/miner/pull/82

This update should fix autolykos_v2 mining.

**Comment by lovemining** [comment]
thank for your great information ,marry christmas  and happy new year
