### ISSUE TITLE
Update the required clang version in linux "clang-10" -> "clang-11"

### ISSUE THREAD

**Issue by kitaniboy** [luminousmining/miner#77]
https://github.com/luminousmining/miner/blob/cac5f82309f2771b3abc7a7022e82744eb970203/CMakeLists.txt#L85-L86

Popular linux distros (e.g., Ubuntu 22.04 apt repository) have deprecated support for clang-10. To ease the environment setting procedure for the compiling, how about updating the required version "clang-10" -> "clang-11" ?

I have checked that the miner can be compiled using clang-11 without errors.

**Comment by luminousmining** [comment]
The problem with clang-11 / Ubuntu 22 is HiveOS. HiveOS use Ubuntu20 by default.
Maybe if we add a condition from OS version we should add clang10 by default and use clang11 for other OS Ubuntu.

**Comment by luminousmining** [comment]
I will try to use clang11 instead of clang10 and run HiveOS to see the results.
`sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev`

**Comment by luminousmining** [comment]
Done : https://github.com/luminousmining/miner/pull/78
Tested on HiveOS.
