### ISSUE TITLE
mining.subscribe failure upon a json response from vipor.net

### ISSUE THREAD

**Issue by kitaniboy** [luminousmining/miner#81]
https://github.com/luminousmining/miner/blob/5c69b7fc083c7ae6e6c03c471b7d419e36436db1/sources/stratum/progpow.cpp#L28-L35

There is `mining.subscribe` failure when connecting to clore pool from vipor.net. Apparently, the cause of the issue is an unsupported structure in the json response. Although I only report this specific use case, I believe the codes should be updated for different algorithms and coins, too.

First, see the examples below. The upper one is the `mining.subscribe` response from 2miners.com, and the lower one is the response from vipor.net.

**2miners.com mining.subscribe response**
```
{"id":1,"result":["0018f158","fa"],"error":null}
``` 
**vipor.net mining.subscribe response**
```
{"result":[[["mining.set_target","0HN89NPDFGH8A"],["mining.notify","0HN89NPDFGH8A"]],"cc3c"],"id":1}
``` 

Currently, the miner experiences two problems when trying to parse the response from vipor.net.
1. **Current code fails if `error` field is not existing in the json response**
Since [boost::json::object::at](https://www.boost.org/doc/libs/1_86_0/libs/json/doc/html/json/ref/boost__json__object/at.html) function throws an error for non-existent keys, [boost::json::object::if_contains](https://www.boost.org/doc/libs/1_86_0/libs/json/doc/html/json/ref/boost__json__object/if_contains.html) should be used instead.

2. **Current code is unable to parse multi-dimensional array**
vipor.net response contains a multi-dimensional array `[[["mining.set_target","0HN89NPDFGH8A"],["mining.notify","0HN89NPDFGH8A"]],"cc3c"]` in the `results` field. However, the current code throws an error (e.g., `out of range [boost.json:17 at /usr/local/include/boost/json/impl/object.ipp:452:44 in function 'try_at']`), failing to parse the multi-dimensional structure.
I have no simple solution for this problem. Perhaps we should replace the boost::json parser with [rapidjson](https://github.com/Tencent/rapidjson), which is the one used by [xmrig](https://github.com/xmrig/xmrig) (which works well on both 2miners.com and vipor.net).

**Comment by luminousmining** [comment]
Thank you for this reports. Maybe vipor use an other stratum version. I will look it.

**Comment by luminousmining** [comment]
The update should fix minig CLOREAI on Vipor: https://github.com/luminousmining/miner/pull/83
The pool doest not add key "error" by default on response.

**Comment by kitaniboy** [comment]
Thank you for the quick response and please ignore the no.2 in the reported problem!
